#!/bin/bash

FILES=`find assets -name \*_.json -print`
FILES=$FILES' '`find assets -name \*copy\*.json -print`

for f in $FILES
do
  dir=`dirname $f`
  mkdir -p "cruft/$dir" 2> /dev/null 
  mv $f "cruft/$dir"
done
